// Hardcoded mock data from CSV exports - for demo purposes only

export const mockCompanies = [
  {
    id: "68de1b4b69f24e492d693ed1",
    name: "MODUS Planning, Design & Engagement",
    industry_sectors: ["consulting"],
    target_regions: ["british_columbia"],
    capabilities: ["urban planning", "rural planning", "urban design"],
    keywords: ["sustainable design", "planning"],
    excluded_keywords: [],
    min_contract_value: null,
    max_contract_value: null,
    certifications: ["B Corp Certified", "Carbon Neutral", "Certified Living Wage"],
    team_size: "",
  },
];

export const mockOpportunities = [
  {
    id: "68de1a0b70d99525c20e3db8",
    rfp_number: "RFP25-15",
    title: "Supply and Delivery of Computer Hardware",
    buyer_organization: "City of Port Moody",
    category: "equipment_supply",
    description: "The City of Port Moody is seeking a qualified vendor to supply and deliver a range of business-class computer hardware. This includes standard desktop PCs, high-performance laptops suitable for graphic-intensive and CPU-demanding applications, standard portable laptops, and monitors.",
    region: "british_columbia",
    deadline: "2025-10-03T14:00:00",
    budget_min: null,
    budget_max: null,
    source_url: "https://portmoody.bidsandtenders.ca/Module/Tenders/en/Tender/Detail/16ad2466-c7a0-411c-80ed-cf1d1712db26/#Addendum",
    documents: [],
    status: "active",
    compliance_notes: "",
  },
  {
    id: "68de1a0b70d99525c20e3db9",
    rfp_number: "25-209",
    title: "Avenue Widening from 200 Street to 202B Street",
    buyer_organization: "Township of Langley",
    category: "construction",
    description: "The Township of Langley is looking for qualified contractors for the following:Widening of approximately 530 meters of arterial roadway on 86 Avenue between 200 Street to 202B Street, including 250-300mm diameter watermain installation, flow meter chamber installation, 600mm diameter concrete culvert extension, concrete curb and gutter, raised medians, concrete bike curbs, multi-use-pathways, boulevard landscaping, street lighting, traffic signals, and communication conduit installation.",
    region: "british_columbia",
    deadline: "2025-10-02T14:00:00",
    budget_min: null,
    budget_max: null,
    source_url: "https://tol.bidsandtenders.ca/Module/Tenders/en/Tender/Detail/d44f105c-92f3-4dac-9ffa-0bd52e43dc0f",
    documents: [],
    status: "active",
    compliance_notes: "",
  },
  {
    id: "68de1a0b70d99525c20e3dba",
    rfp_number: "RFQ 25-245",
    title: "Supply & Delivery of Bottled Water & Rental Coolers",
    buyer_organization: "Township of Langley",
    category: "equipment_supply",
    description: "The Corporation of the Township of Langley requests Quotations from an experienced and qualified vendor to supply and delivery of bottled water, rental coolers, and Point-of-Use (POU) units at various locations throughout the Township of Langley. The Supplier must provide semi-annual filtration, sanitation and inspection services and provide a written report for each cooler and unit.",
    region: "british_columbia",
    deadline: "2025-09-24T10:00:00",
    budget_min: null,
    budget_max: null,
    source_url: "https://tol.bidsandtenders.ca/Module/Tenders/en/Tender/Detail/1c933417-98f7-492a-8d11-dfe94b3a9308",
    documents: [],
    status: "active",
    compliance_notes: "",
  },
  {
    id: "68de1a0b70d99525c20e3dbb",
    rfp_number: "4037",
    title: "Supply and Deliver Emergency Sleeping Cots",
    buyer_organization: "City of Nanaimo",
    category: "equipment_supply",
    description: "The City is seeking to procure emergency sleeping cots to support sheltering efforts during evacuations caused by emergencies and disasters. The objective is to acquire a minimum of 500 sleeping surfaces within a maximum budget of CAD 145,000. The actual quantity ordered will depend on the unit rate proposed by the Successful Proponent, with the goal of maximizing the number of sleeping surfaces that can be procured within the stated budget of CAD 145,000. Sleeping surfaces may be provided through...",
    region: "british_columbia",
    deadline: "2025-10-15T15:00:00",
    budget_min: null,
    budget_max: 145000,
    source_url: "https://nanaimo.bidsandtenders.ca/Module/Tenders/en/Tender/Detail/761fb558-f6e4-4b42-abf9-e59cfc027f43",
    documents: [],
    status: "active",
    compliance_notes: "",
  },
  {
    id: "68de1a0b70d99525c20e3dbe",
    rfp_number: "RFI-2025-8-4701",
    title: "Rental of Light Duty Vehicles for Fleet Vehicle Agency",
    buyer_organization: "Government of Yukon",
    category: "other",
    description: "Yukon Governments (YG) Fleet Vehicle Agency (FVA) at the Department of Highways and Public Works is requesting information (RFI) for light duty vehicle rentals for a standing offer agreement of up to 3 years",
    region: "british_columbia",
    deadline: "2025-10-01T16:00:00",
    budget_min: null,
    budget_max: null,
    source_url: "https://yukon.bidsandtenders.ca/Module/Tenders/en/Tender/Detail/9eaa191a-663f-46e9-80c1-8431c08f8831/#PlanTaker",
    documents: [],
    status: "active",
    compliance_notes: "",
  },
  {
    id: "68de1a0b70d99525c20e3dbf",
    rfp_number: "RFB-2025-7-4626",
    title: "Ross River Snow Clearing",
    buyer_organization: "Government of Yukon",
    category: "construction",
    description: "Snow clearing of roadways, parking lots, sidewalks, stairs, vehicle traffic areas, entrances and loading areas at various buildings in Ross River, YukonCommunity: Ross RiverTraditional Territory: Ross River Dena Council",
    region: "british_columbia",
    deadline: "2025-09-22T16:00:00",
    budget_min: null,
    budget_max: null,
    source_url: "https://yukon.bidsandtenders.ca/Module/Tenders/en/Tender/Detail/26ebcf0f-80dc-4db4-ac08-9a67bb1df568/#PlanTaker",
    documents: [],
    status: "active",
    compliance_notes: "",
  },
  {
    id: "68de1a0b70d99525c20e3dc0",
    rfp_number: "RFP-2025-95",
    title: "Storm Sewer Rehabilitation Analysis",
    buyer_organization: "City of Grande Prairie",
    category: "engineering",
    description: "The City of Grande Prairie (the \"City\") is requesting detailed and comprehensive proposals from Engineering consulting firms specializing in underground storm sewer rehabilitation and trenchless technologies to provide non-destructive testing and Engineering evaluation for the 2025 Storm Sewer Rehabilitation Analysis project. The successful proponent (the \"Consultant\") will provide non-destructive testing services, preliminary Engineering, asset inspection and analysis, and technical report preparation...",
    region: "british_columbia",
    deadline: "2025-09-23T14:00:00",
    budget_min: null,
    budget_max: null,
    source_url: "https://cityofgp.bidsandtenders.ca/Module/Tenders/en/Tender/Detail/3a46a493-35fd-4b5e-8827-496a804fa4a0",
    documents: [],
    status: "active",
    compliance_notes: "",
  },
  {
    id: "68de1a0b70d99525c20e3dc1",
    rfp_number: "RFP 1220-2025-3689S2",
    title: "Works Management System (CMMS or EAM)",
    buyer_organization: "City of Abbotsford",
    category: "software_development",
    description: "This Request for Proposals (the \"RFP\") is an invitation by the City of Abbotsford (the \"City\") to prospective proponents to submit proposals for City of Abbotsford – Works Management System (CMMS or EAM), as further described in Section A of the RFP Particulars (Appendix B) (the \"Deliverables\"). Previous RFPQ IssuedThe City issued RFPQ 1220-2025-3689S1 – City of Abbotsford – Works Management System (CMMS or EAM) on April 22, 2025. On closing, May 20, 2025, the submissions were evaluated but as per...",
    region: "british_columbia",
    deadline: "2025-10-07T14:00:00",
    budget_min: null,
    budget_max: null,
    source_url: "https://abbotsford.bidsandtenders.ca/Module/Tenders/en/Tender/Detail/1e087733-a743-4bc2-a6ad-971b28a6e71b",
    documents: [],
    status: "active",
    compliance_notes: "",
  },
];

// Map opportunity IDs from rfp_number to id for matches
const opportunityIdMap = {
  "RFP25-15": "68de1a0b70d99525c20e3db8",
  "25-209": "68de1a0b70d99525c20e3db9",
  "RFQ_25-245": "68de1a0b70d99525c20e3dba",
  "4037": "68de1a0b70d99525c20e3dbb",
  "RFI-2025-8-4701": "68de1a0b70d99525c20e3dbe",
  "RFB-2025-7-4626": "68de1a0b70d99525c20e3dbf",
  "RFP-2025-95": "68de1a0b70d99525c20e3dc0",
  "RFP_1220-2025-3689S2": "68de1a0b70d99525c20e3dc1",
};

export const mockOpportunityMatches = [
  {
    id: "68de04e312cc6677e1ff1c0c",
    company_id: "68de1b4b69f24e492d693ed1",
    opportunity_id: opportunityIdMap["RFP25-15"],
    relevance_score: 53.5,
    match_rationale: "This computer hardware supply opportunity shows strong relevance based on the scale and professional nature of the procurement. While not directly aligned with your planning and design expertise, the opportunity represents a significant municipal contract with potential for strategic partnerships.",
    risk_notes: "Outside core competency area - equipment supply vs consulting services",
    actionability: "medium",
    tags: [],
    status: "new",
    notes: "",
  },
  {
    id: "68de04e312cc6677e1ff1c0d",
    company_id: "68de1b4b69f24e492d693ed1",
    opportunity_id: opportunityIdMap["25-209"],
    relevance_score: 91.5,
    match_rationale: "Excellent alignment with urban design capabilities! This avenue widening project includes multi-use pathways, boulevard landscaping, and complete streets elements that directly match your urban planning and sustainable design expertise. The project scope encompasses urban design principles you specialize in.",
    risk_notes: "Requires construction management expertise as prime contractor - may be better suited as urban design subconsultant",
    actionability: "high",
    tags: ["strategic_fit", "subcontractor_suitable"],
    status: "saved",
    notes: "Strong fit for urban design components - explore partnership opportunities",
  },
  {
    id: "68de04e312cc6677e1ff1c0e",
    company_id: "68de1b4b69f24e492d693ed1",
    opportunity_id: opportunityIdMap["RFQ_25-245"],
    relevance_score: 47.6,
    match_rationale: "This bottled water and cooler supply opportunity is outside your core consulting services but represents ongoing municipal procurement that could provide relationship building opportunities with Township of Langley.",
    risk_notes: "Not aligned with planning and design services - equipment supply focus",
    actionability: "low",
    tags: [],
    status: "dismissed",
    notes: "Outside service offerings",
  },
  {
    id: "68de04e312cc6677e1ff1c0f",
    company_id: "68de1b4b69f24e492d693ed1",
    opportunity_id: opportunityIdMap["4037"],
    relevance_score: 52.5,
    match_rationale: "Emergency preparedness and sheltering infrastructure represents a specialized procurement area. While outside traditional planning scope, there may be opportunities to support municipal emergency management planning initiatives.",
    risk_notes: "Equipment supply focus - minimal planning component",
    actionability: "low",
    tags: [],
    status: "reviewed",
    notes: "",
  },
  {
    id: "68de04e312cc6677e1ff1c12",
    company_id: "68de1b4b69f24e492d693ed1",
    opportunity_id: opportunityIdMap["RFI-2025-8-4701"],
    relevance_score: 76.4,
    match_rationale: "Vehicle fleet management RFI from Yukon Government. While this is information gathering for vehicle rentals, it indicates broader fleet and transportation planning needs that could align with your sustainable transportation consultation capabilities.",
    risk_notes: "Current RFI is for vehicle rentals only - not planning services",
    actionability: "medium",
    tags: [],
    status: "reviewed",
    notes: "Monitor for future transportation planning opportunities from this client",
  },
  {
    id: "68de04e312cc6677e1ff1c13",
    company_id: "68de1b4b69f24e492d693ed1",
    opportunity_id: opportunityIdMap["RFB-2025-7-4626"],
    relevance_score: 61.4,
    match_rationale: "Snow clearing services for Ross River facilities. Limited planning component, though demonstrates ongoing Yukon Government procurement activity and potential for future community development planning opportunities in the region.",
    risk_notes: "Operational services contract - no planning element",
    actionability: "low",
    tags: [],
    status: "new",
    notes: "",
  },
  {
    id: "68de04e312cc6677e1ff1c14",
    company_id: "68de1b4b69f24e492d693ed1",
    opportunity_id: opportunityIdMap["RFP-2025-95"],
    relevance_score: 80.4,
    match_rationale: "Engineering consulting for storm sewer analysis requires specialized civil engineering expertise in underground infrastructure. While infrastructure planning connects to urban systems, this is a technical engineering assessment rather than planning or design work.",
    risk_notes: "Requires civil engineering specialization in underground utilities - outside core planning capabilities",
    actionability: "low",
    tags: [],
    status: "new",
    notes: "",
  },
  {
    id: "68de04e312cc6677e1ff1c15",
    company_id: "68de1b4b69f24e492d693ed1",
    opportunity_id: opportunityIdMap["RFP_1220-2025-3689S2"],
    relevance_score: 88.4,
    match_rationale: "Software development for works management system (CMMS/EAM). This IT procurement is outside your planning and design services, though understanding municipal asset management systems could complement infrastructure planning work.",
    risk_notes: "Software development project - no planning or design component",
    actionability: "low",
    tags: [],
    status: "new",
    notes: "",
  },
];
